
services:
  db:
    image: mysql:8.0
    container_name: project_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project007
      MYSQL_USER: anzhela
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"